### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by unlight** [uittorio/jest-ts-auto-mock#30]
```
git clone https://github.com/Typescript-TDD/jest-ts-auto-mock
cd jest-ts-auto-mock
npm i
npm run build
cd examples\ts-jest-ttypescript
npm i
npm t
```

```
 FAIL  reuse/2.test.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'map' of undefined

      at transformBundle (node_modules/typescript/lib/typescript.js:77498:53)

 FAIL  reuse/1.test.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'map' of undefined

      at transformBundle (node_modules/typescript/lib/typescript.js:77498:53)

 FAIL  ./basic.test.ts
  ● Test suite failed to run

    TypeError: Cannot read property 'map' of undefined

      at transformBundle (node_modules/typescript/lib/typescript.js:77498:53)
```

**Comment by uittorio** [comment]
Oh no!! I will have a look :) thanks for reporting the issue

**Comment by uittorio** [comment]
I've created a new version 2.0.0 @unlight

**Comment by unlight** [comment]
@uittorio 
Does it work for you?
It doesn't for me, still same errors.

**Comment by uittorio** [comment]
Tests are working on the pipeline. Could try to delete the node modules in both folders ( main and examples) and try again?

**Comment by unlight** [comment]
I did that

**Comment by uittorio** [comment]
Which version of node are you using?

**Comment by uittorio** [comment]
You are right, I've just reproduced it.

**Comment by uittorio** [comment]
So, I am not sure what is going on. I have tried to re install the modules again. I've checked and it was using an old version typescript.
